#!/usr/bin/env -S deno run --allow-env --allow-write --allow-read
// Local-only helper to mint test JWTs for QA harness fixtures (KAN-44, KAN-82, …).
// Reads JWT_SECRET from env and signs HS256 tokens with the required claims, then
// drops the resulting env-var lines into ~/.replant/qa-<ticket>.env (mode 0600).
//
// SEC 10933 governs this script. It must:
//   - never hardcode JWT_SECRET
//   - never log JWT_SECRET
//   - never echo JWT bodies to stdout
//   - stamp every minted JWT with super_admin=false, test_fixture=true,
//     test_ticket=<ticket> for downstream filtering / sweep
//
// Operator (Ife only — the seat holding JWT_SECRET) runs:
//
//   JWT_SECRET="..." deno run --allow-env --allow-write --allow-read \
//     supabase/functions/_shared/mint-test-jwt.ts \
//     --ticket KAN-44 --ttl-minutes 60 \
//     --fixture ACTIVE=<uuid> \
//     --fixture PENDING_FUTURE=<uuid> \
//     --fixture PENDING_PAST=<uuid> \
//     --fixture DEACTIVATED_CRON=<uuid>
//
// Output: ~/.replant/qa-kan-44.env containing
//   KAN44_JWT_ACTIVE=<jwt>
//   KAN44_JWT_PENDING_FUTURE=<jwt>
//   …
//
// Stdout shows fixture count, expiry timestamp, and drop path. Nothing else.

interface Fixture { key: string; uuid: string }
interface CliArgs { ticket: string; ttlMinutes: number; fixtures: Fixture[] }

function usage(): never {
  console.error(
    "Usage: deno run --allow-env --allow-write --allow-read mint-test-jwt.ts \\\n" +
    "         --ticket KAN-XX [--ttl-minutes N] --fixture KEY=UUID [--fixture …]",
  );
  Deno.exit(2);
}

function parseArgs(argv: string[]): CliArgs {
  let ticket = "";
  let ttlMinutes = 60;
  const fixtures: Fixture[] = [];
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === "--ticket")            ticket = argv[++i] ?? "";
    else if (a === "--ttl-minutes")  ttlMinutes = Number.parseInt(argv[++i] ?? "", 10);
    else if (a === "--fixture") {
      const v = argv[++i] ?? "";
      const eq = v.indexOf("=");
      if (eq <= 0) { console.error(`--fixture must be KEY=UUID, got: ${v}`); Deno.exit(2); }
      fixtures.push({ key: v.slice(0, eq), uuid: v.slice(eq + 1) });
    }
    else if (a === "-h" || a === "--help") usage();
    else { console.error(`unknown arg: ${a}`); usage(); }
  }
  if (!ticket || !/^[A-Z]+-\d+$/.test(ticket)) { console.error("--ticket required, format e.g. KAN-44"); usage(); }
  if (!Number.isFinite(ttlMinutes) || ttlMinutes <= 0) { console.error("--ttl-minutes must be a positive integer"); usage(); }
  if (fixtures.length === 0) { console.error("at least one --fixture KEY=UUID required"); usage(); }
  for (const f of fixtures) {
    if (!/^[A-Z][A-Z0-9_]*$/.test(f.key)) { console.error(`fixture key must be UPPER_SNAKE: ${f.key}`); Deno.exit(2); }
    if (!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(f.uuid)) {
      console.error(`fixture uuid must be a UUID: ${f.uuid}`);
      Deno.exit(2);
    }
  }
  return { ticket, ttlMinutes, fixtures };
}

function b64url(bytes: Uint8Array): string {
  let bin = "";
  for (let i = 0; i < bytes.length; i++) bin += String.fromCharCode(bytes[i]);
  return btoa(bin).replace(/=+$/, "").replace(/\+/g, "-").replace(/\//g, "_");
}

async function signHS256(payload: Record<string, unknown>, secret: string): Promise<string> {
  const enc = new TextEncoder();
  const headerB64 = b64url(enc.encode(JSON.stringify({ alg: "HS256", typ: "JWT" })));
  const payloadB64 = b64url(enc.encode(JSON.stringify(payload)));
  const data = `${headerB64}.${payloadB64}`;
  const key = await crypto.subtle.importKey(
    "raw",
    enc.encode(secret),
    { name: "HMAC", hash: "SHA-256" },
    false,
    ["sign"],
  );
  const sigBytes = new Uint8Array(await crypto.subtle.sign("HMAC", key, enc.encode(data)));
  return `${data}.${b64url(sigBytes)}`;
}

const args = parseArgs(Deno.args);

const secret = Deno.env.get("JWT_SECRET");
if (!secret) {
  console.error("ERROR: JWT_SECRET env var not set. Set it before running this script.");
  Deno.exit(2);
}

const home = Deno.env.get("HOME");
if (!home) {
  console.error("ERROR: HOME env var not set.");
  Deno.exit(2);
}

const now = Math.floor(Date.now() / 1000);
const exp = now + args.ttlMinutes * 60;
const expIso = new Date(exp * 1000).toISOString();

// Ticket-derived env-var prefix: KAN-44 -> KAN44, KAN-82 -> KAN82, etc.
const varPrefix = args.ticket.replace(/-/g, "").toUpperCase();
const fileSlug = args.ticket.toLowerCase();

const lines: string[] = [
  `# Test JWTs for ${args.ticket}`,
  `# TTL: ${args.ttlMinutes} minutes — expires ${expIso}`,
  `# Generated by supabase/functions/_shared/mint-test-jwt.ts (per SEC 10933)`,
  `# DO NOT COMMIT. Mode 0600. Each JWT carries:`,
  `#   super_admin: false   test_fixture: true   test_ticket: "${args.ticket}"`,
  "",
];

for (const f of args.fixtures) {
  const payload = {
    sub: f.uuid,
    iat: now,
    exp,
    aud: "authenticated",
    role: "authenticated",
    super_admin: false,
    test_fixture: true,
    test_ticket: args.ticket,
  };
  const jwt = await signHS256(payload, secret);
  lines.push(`${varPrefix}_JWT_${f.key}=${jwt}`);
}

const dir = `${home}/.replant`;
const outPath = `${dir}/qa-${fileSlug}.env`;

await Deno.mkdir(dir, { recursive: true });
await Deno.writeTextFile(outPath, lines.join("\n") + "\n");
try {
  await Deno.chmod(outPath, 0o600);
} catch (e) {
  console.error(`WARN: could not set 0600 on ${outPath} (${(e as Error).message}). Set manually: chmod 600 ${outPath}`);
}

// Confirmation only — NO JWT bodies, NO secret.
console.log(`Minted ${args.fixtures.length} JWTs for ${args.ticket}`);
console.log(`  TTL:        ${args.ttlMinutes} minutes`);
console.log(`  Expires:    ${expIso}`);
console.log(`  Drop path:  ${outPath}`);
console.log(`  File mode:  0600`);
console.log("");
console.log(`Source the file before running the harness:`);
console.log(`  set -a && . ${outPath} && set +a`);
