-- F11 — display_name_preference was INERT platform-wide (Founder device pass 2026-07-27)
--
-- Founder changed her setting to "role + full name", then back to "role +
-- first name", and her comment still rendered "Minister Ruth James".
--
-- ROOT CAUSE: public.resolve_display_name gated only the MIDDLE name on the
-- preference; the family name was appended unconditionally. Since most
-- leaders have no middle name, the setting did nothing at all. 184 of 221
-- leaders had chosen 'first_name_only' and were having a surname they opted
-- out of showing rendered on every leader-facing surface. This is the F11
-- defect first observed in the 2026-07-12 sim UAT, now root-caused.
--
-- FIXED HERE (all APPLIED LIVE 2026-07-27):
--   1. resolve_display_name — 'first_name_only' now means role + first name,
--      no surname. 'full_name' keeps given (+middle) + family with the
--      last_name_first ordering. Falls back to the family name when no first
--      name exists, so a bare title is never a whole attribution.
--      This single change corrects every resolver-backed surface at once:
--      comments, prayer wall, testimonies, Connect threads, branch members,
--      blocked users, church profile, content bylines.
--   2. search_leaders — returned RAW full_name (Connect search). Now returns
--      the resolved name, plus a new avatar_initial column taken from the
--      NAME rather than the role prefix the byline leads with.
--   3. get_invite_candidates — returned RAW full_name in its leaders jsonb.
--      Now resolved.
--   4. find_nearby_churches — emitted a derived surname to the church-map
--      edge function. last_name is now NULL unless the leader chose
--      'full_name'.
--
-- Matching still spans the stored full_name so a leader stays findable by
-- surname; only the DISPLAYED value honours the preference. Flagged for the
-- pen-test window: that asymmetry is a mild confirmation oracle.
--
-- ADMIN surfaces intentionally untouched — get_prayer_wall / get_testimonies
-- / get_open_prayers expose raw full_name ONLY inside their super_admin
-- branch, which is legitimate oversight.
--
-- Function bodies are the live definitions; this file is the record. Not in
-- supabase_migrations by this wave's batch convention.

-- ── ADDENDUM (same day, Founder): include_middle_name honoured ──────────
-- Settings has a dedicated "show middle name" toggle (users.include_middle_name)
-- that resolve_display_name ignored entirely — it keyed middle-name display
-- off display_name_preference instead. 13 leaders had the toggle on; 2 of
-- them in full_name mode were silently NOT getting their middle name.
--
-- resolve_display_name gains an 8th arg, p_include_middle (DEFAULT false so
-- every legacy 7-arg call site keeps compiling). Middle name renders only
-- when the leader is in full_name mode AND has the toggle on; first_name_only
-- ignores it entirely. last_name_first ordering still applies.
--
-- All 12 calling functions re-issued to thread u.include_middle_name through:
--   content_named_leader_label · get_blocked_users · get_branch_members
--   get_church_profile · get_comments · get_invite_candidates
--   get_landing_testimonies · get_leader_thread_list · get_open_prayers
--   get_prayer_wall · get_testimonies · search_leaders
-- Verified live: "Psalmist Ruth Ifee Test" (full + toggle on) vs
-- "Pastor Hrang Cung" (full, toggle off, middle "Lal" suppressed).

-- ── ADDENDUM 2 — overload collapsed to ONE canonical function ───────────
-- Adding p_include_middle created a SECOND overload rather than replacing
-- the 7-arg version (Postgres treats a new parameter as a new signature,
-- even with a DEFAULT). Both carried the F11 fix, but only the 8-arg one
-- honoured the middle toggle — so any future 7-arg call site would have
-- silently lost middle-name support. The 7-arg overload is DROPPED: there
-- is now exactly one resolve_display_name, and a 7-arg call resolves to it
-- with p_include_middle defaulting false (safe).
--
-- Verified live after the drop, all three axes independently honoured:
--   full + given-first + middle ON  -> "Pastor Mei Ling Chen"
--   full + FAMILY-first + middle ON -> "Pastor Chen Mei Ling"
--   full + family-first + middle OFF-> "Pastor Chen Mei"
--   first_name_only (ignores both)  -> "Pastor Mei"
