-- KAN-293/295/296/292 — Extend audit_log_action_check with 8 new actions
--
-- Existing 64 actions read from live constraint via pg_get_constraintdef 2026-06-30.
-- Copied verbatim below; new 8 actions appended.

ALTER TABLE public.audit_log DROP CONSTRAINT audit_log_action_check;

ALTER TABLE public.audit_log ADD CONSTRAINT audit_log_action_check CHECK (
  action = ANY (ARRAY[
    -- Existing 64 actions (verbatim from pg_get_constraintdef 2026-06-30)
    'read_region',
    'read_heartcry',
    'verify_church',
    'reject_church',
    'flag_cleared',
    'flag_escalated',
    'flag_read',
    'pii_scrubbed',
    'deactivate_church',
    'deactivate_user',
    'announcement_deleted',
    'team_member_added',
    'team_member_removed',
    'rag_overridden',
    'rag_override_removed',
    'reinstate_church',
    'super_admin_granted',
    'super_admin_revoked',
    'admin_session_refreshed',
    'admin_password_reset',
    'admin_step_up_reauth',
    'heartcry_responded',
    'flag_queue_opened',
    'underground_oversight_opened',
    'announcement_created',
    'pastoral_signal_seen',
    'pastoral_signal_dispositioned',
    'pastoral_context_expanded',
    'pastoral_digest_emitted',
    'church_details_updated',
    'admin_aal2_elevation',
    'admin_mfa_factor_reset',
    'underground_aal2_gate',
    'heartcry_aal2_gate',
    'admin_password_reset_sent',
    'prayer_request_withdrawn',
    'heartcry_feed_consent_retracted',
    'church_location_updated',
    'branch_created',
    'branch_invite_responded',
    'branch_member_removed',
    'branch_activated',
    'verify_leader',
    'reject_leader',
    'edit_pending',
    'welcome_dm_sent',
    'replant_team_reply_sent',
    'comment_posted',
    'heartcry_feed_approved',
    'branch_left',
    'branch_name_edited',
    'branch_leader_removed',
    'branch_deleted',
    'branch_parent_auto_linked',
    'branch_parent_admin_linked',
    'admin_tier_promotion_requested',
    'admin_tier_promotion_approved',
    'admin_tier_promotion_denied',
    'admin_tier_promotion_expired',
    'admin_invite_sent',
    'admin_demote',
    'admin_revoke',
    'account_name_updated',
    'admin_grant_to_existing_user',
    -- NEW for KAN-293/295/296/292 (Escalated Cases bundle)
    'escalated_case_created',
    'escalated_case_auto_routed',
    'escalated_proposal_proposed',
    'escalated_proposal_approved',
    'escalated_proposal_rejected',
    'escalated_case_closed',
    'escalated_inbox_opened',
    'escalated_case_reach_out_sent'
  ])
);
