#!/usr/bin/env node
// Generate the KAN-44 QA report.md from artifacts produced by Pass 1 + Pass 2.
//
// Usage:
//   node generate-report.mjs --sample --out <path>          # placeholder report (dry-run)
//   node generate-report.mjs --artifacts <dir> --out <path> # populated report

import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { dirname } from "node:path";

const args = process.argv.slice(2);
const sampleMode = args.includes("--sample");
const outIdx = args.indexOf("--out");
const out = outIdx === -1 ? null : args[outIdx + 1];
const artIdx = args.indexOf("--artifacts");
const artifactsDir = artIdx === -1 ? null : args[artIdx + 1];

if (!out) {
  console.error("ERROR: --out <path> required");
  process.exit(2);
}

let pass1, pass2, started, finished, fnId, fnVersion;

if (sampleMode) {
  // Placeholder values for dry-run preview
  started = "<UTC-timestamp-start>";
  finished = "<UTC-timestamp-end>";
  fnId = "<deployed function id>";
  fnVersion = "<v>";
  pass1 = {
    "TC-44.1 active":             { status: "<PENDING>", rt_ms: "<n>" },
    "TC-44.2 pending+future":     { status: "<PENDING>", rt_ms: "<n>", days_remaining: "<n>" },
    "TC-44.3 pending+past Opt-B": { status: "<PENDING>", rt_ms: "<n>", audit_row: "<written|missing>" },
    "TC-44.3a idempotency":       { status: "<PENDING>", rt_ms: "<n>", new_audit_row: "<no>" },
    "TC-44.4 cron-deactivated":   { status: "<PENDING>", "byte_identical_to_44.3": "<true|false>" },
    "TC-44.5 401 paths (3)":      { status: "<PENDING>", subcases: "no-jwt | anon | malformed" },
    "TC-44.6 5xx":                { status: "<PENDING|N/A>", note: "synthetic injection if available" },
    "TC-44.7 non-leak":           { status: "<PENDING>", note: "cross-path body byte equality" },
  };
  pass2 = {
    "2.1 day-boundary sweep":     { status: "<PENDING>" },
    "2.2 concurrent Option-B":    { status: "<PENDING>" },
    "2.3 JWT edge cases":         { status: "<PENDING>" },
    "2.4 DB edge cases":          { status: "<PENDING|SKIPPED if no SR key>" },
    "2.5 rapid-fire (50–100x)":   { status: "<PENDING>", calls: "<n>", matched: "<n>" },
    "2.6 forge attempt":          { status: "<PENDING>" },
    "2.7 timing":                 { p50_ms: "<n>", p95_ms: "<n>" },
  };
} else if (artifactsDir) {
  const summary = JSON.parse(readFileSync(`${artifactsDir}/summary.json`, "utf8"));
  ({ started, finished, fnId, fnVersion, pass1, pass2 } = summary);
} else {
  console.error("ERROR: --sample or --artifacts <dir> required");
  process.exit(2);
}

const lines = [];
lines.push("# KAN-44 QA TESTING REPORT");
lines.push("");
lines.push(`**Function:** auth-status-check (id ${fnId}, version ${fnVersion})`);
lines.push(`**Started / Finished (UTC):** ${started} → ${finished}`);
lines.push("");
lines.push("## Pass 1 — Formal TCs");
for (const [name, r] of Object.entries(pass1)) {
  const extras = Object.entries(r).filter(([k]) => k !== "status").map(([k, v]) => `${k}=${v}`).join("  ");
  lines.push(`- ${name}: **${r.status ?? "—"}**  ${extras}`);
}
lines.push("");
lines.push("## Pass 2 — Adversarial");
for (const [name, r] of Object.entries(pass2)) {
  const extras = Object.entries(r).filter(([k]) => k !== "status").map(([k, v]) => `${k}=${v}`).join("  ");
  lines.push(`- ${name}: **${r.status ?? "—"}**  ${extras}`);
}
lines.push("");
lines.push("## Verdict");
lines.push(sampleMode ? "<PASS|FAIL — populated by run.sh after artifacts complete>" : "<TBD>");
lines.push("");
lines.push("## Artifacts");
lines.push(sampleMode ? `<this will point at qa/kan-44/artifacts/<UTC-timestamp>/>` : `qa/kan-44/artifacts/${(artifactsDir || "").split("/").pop()}/`);
lines.push("");
lines.push("---");
lines.push("Generated by qa/kan-44/generate-report.mjs.");

const content = lines.join("\n") + "\n";
mkdirSync(dirname(out), { recursive: true });
writeFileSync(out, content);
console.log(`Report written to ${out} (${lines.length} lines)`);
